server:
  port: 8081

spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/solar_ai
      auto-index-creation: true
  kafka:
    bootstrap-servers: localhost:29092

logging:
  level:
    org.springframework.data.mongodb: INFO
    org.apache.kafka: INFO
    org.springframework.kafka.core.KafkaAdmin: DEBUG
