server:
  port: 8081

spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/solar_ai
      auto-index-creation: true
  kafka:
    bootstrap-servers: localhost:29092

    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      acks: all            # wait for broker ack; safer in dev
      retries: 3
      properties:
        delivery.timeout.ms: 120000
        request.timeout.ms: 30000

    topics:
      summary-requests: summary_requests
      summary-results: summary_results  # if you add a results topic later
      consumer:
        concurrency: 1

logging:
  level:
    org.springframework.data.mongodb: INFO
    org.apache.kafka: INFO
    org.springframework.kafka.core.KafkaAdmin: DEBUG
